# Generated by Django 2.0.2 on 2018-02-26 22:34

import apps.clients.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(default='', max_length=32, verbose_name='first name')),
                ('last_name', models.CharField(default='', max_length=32, verbose_name='last name')),
                ('birth_date', models.DateField(default=None, verbose_name='birth date')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.clients.models.upload_photo, verbose_name='photo')),
                ('rating', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='rating')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
    ]
